# Generated by Django 6.0 on 2026-01-06 21:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True, validators=[core.validators.validate_no_digits], verbose_name='Username'),
        ),
    ]
