# Generated by Django 6.0 on 2026-01-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_searchhistory_viewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'house_number', 'apartment_number', 'city', 'postal_code')},
        ),
    ]
