# Generated by Django 6.0 on 2026-01-05 14:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_address_apartment_number_address_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=70, validators=[core.validators.validate_no_digits]),
        ),
        migrations.AlterField(
            model_name='address',
            name='land',
            field=models.CharField(choices=[('baden_wurttemberg', 'Baden-Württemberg'), ('bayern', 'Bayern'), ('berlin', 'Berlin'), ('brandenburg', 'Brandenburg'), ('bremen', 'Bremen'), ('hamburg', 'Hamburg'), ('hessen', 'Hessen'), ('mecklenburg_vorpommern', 'Mecklenburg-Vorpommern'), ('niedersachsen', 'Niedersachsen'), ('nordrhein_westfalen', 'Nordrhein-Westfalen'), ('rheinland_pfalz', 'Rheinland-Pfalz'), ('saarland', 'Saarland'), ('sachsen', 'Sachsen'), ('sachsen_anhalt', 'Sachsen-Anhalt'), ('schleswig_holstein', 'Schleswig-Holstein'), ('thuringen', 'Thüringen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, validators=[core.validators.validate_no_digits]),
        ),
    ]
