# Generated by Django 6.0 on 2026-01-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimg',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
